export const AUTHOR = {
  name: "אבי ויזל",
  org: "IBM Israel",
  email: "aviv@il.ibm.com",
  phone: "050-729-2012",
  year: "2026",
};

export const CAPSTONE = {
  name: "TaskFlow",
  desc: "מערכת ניהול משימות צוותית — פרויקט Capstone שבונים לאורך פרקים 11–28",
  stack: "HTML + CSS + JavaScript (Vanilla) · Python + Flask · SQLite",
};

export const PHASES = [
  { id: "foundation", label: "יסודות", chapters: [1, 2, 3, 4] },
  { id: "bob", label: "עבודה עם Bob", chapters: [5, 6, 7, 8, 9, 10] },
  { id: "product", label: "מוצר ותכנון", chapters: [11, 12, 13, 14] },
  { id: "build", label: "בניית Capstone", chapters: [15, 16, 17, 18, 19] },
  { id: "ai", label: "AI וכלים", chapters: [20, 21, 22, 23] },
  { id: "quality", label: "איכות ותפעול", chapters: [24, 25, 26, 27, 28] },
  { id: "enterprise", label: "Enterprise: IBM i · Z · Java · Orchestrate · On-Prem", chapters: [29, 30, 31, 32, 33, 34] },
];

export const CHAPTERS = [
  {
    num: 1,
    title: "מהי מערכת תוכנה?",
    subtitle: "להבין ממה בנויה תוכנה ואיך מידע נע בין החלקים שלה",
    phase: "foundation",
    time: "25 דק'",
    intro: "כשאנחנו לוחצים על כפתור באפליקציה, נראה רק מסך אחד. מאחורי הקלעים פועלים כמה שכבות: ממשק, שרת, מסד נתונים — וכל אחת עם תפקיד שונה. בפרק זה נבנה תמונה מנטלית שתלווה אתכם בכל הקורס.",
    concepts: [
      { term: "קלט, עיבוד ופלט", def: "קלט = מה שהמשתמש מוסר. עיבוד = החישוב או ההחלטה. פלט = התוצאה שחוזרת.", example: "בטופס הרשמה: קלט = שם ואימייל, עיבוד = בדיקת תקינות, פלט = הודעת הצלחה.", pitfall: "אם מדלגים על שלב — קשה לדעת איפה נשבר." },
      { term: "Frontend", def: "החלק שהמשתמש רואה: כפתורים, טפסים, רשימות.", example: "דף רשימת משימות ב-TaskFlow.", pitfall: "Frontend לא שומר מידע לצמיתות לבד." },
      { term: "Backend ו-API", def: "השרת מבצע כללים עסקיים; ה-API הוא חוזה התקשורת.", example: "POST /tasks יוצר משימה חדשה.", pitfall: "לבלבל בין API (דרך גישה) לבין DB (אחסון)." },
      { term: "Database", def: "מאגר מידע ששרד אחרי סגירת האפליקציה.", example: "טבלת tasks עם id, title, status.", pitfall: "לשמור מידע רק בזיכרון הדפדפן." },
      { term: "Request / Response", def: "הלקוח שולח request, השרת מחזיר response. שניהם מכילים headers + body.", example: "GET /tasks → 200 OK + [{id:1, title:'...'}]", pitfall: "לטפל רק ב-happy path ולהתעלם מ-4xx/5xx." },
      { term: "Stateless", def: "כל request עומד בפני עצמו — השרת לא זוכר את הקודם. State נשמר ב-DB או session.", example: "API שמקבל token בכל בקשה — לא מסתמך על 'זוכרים אותך'.", pitfall: "לאחסן state ב-memory של השרת — נאבד בהפעלה מחדש." },
    ],
    analogy: { text: "כל שכבה עושה בדיוק דבר אחד: Frontend מציג ואוסף, Backend מחליט ומאמת, Database שומר. כשמשהו נשבר — הבדלת האחריות מצביעה מיד על השכבה הכשולה. מערכות ללא הפרדה כזו הופכות ל-«big ball of mud» — שגיאה אחת משפיעה על הכל.", bridge: "פתחו את TaskFlow ב-Ask. בקשו מ-Bob לצייר את מסלול הנתונים מ-«לחיצת כפתור הוספה» עד «שמירה ב-DB» — לא קוד, רק flow. בדקו: האם כל שכבה מופיעה? האם ה-flow מתאים ל-diagram שבפרק?" },
    diagram: `<div class="flow-diagram"><div class="flow-node primary">משתמש</div><span class="flow-arrow">→</span><div class="flow-node">Frontend</div><span class="flow-arrow">→</span><div class="flow-node secondary">API</div><span class="flow-arrow">→</span><div class="flow-node">Backend</div><span class="flow-arrow">→</span><div class="flow-node storage">Database</div></div><p style="font-size:0.85rem;color:var(--ink-secondary);margin-top:0.25rem">כיוון הבקשה (request): משתמש → Frontend → API → Backend → Database. התגובה (response) חוזרת בכיוון הפוך.</p>`,
    bob: { modes: ["Ask"], workflow: "בפרק פתיחה עובדים ב-Ask בלבד — Bob מסביר, לא נוגע בקוד.", prompt: "In Ask mode: analyze @src. Explain Frontend, Backend, and DB, and the path from clicking Add Task until it appears on screen. Do not change files.", promptWhy: "מגדירה Mode, תחום (@), תוצר מילולי וגבול ברור." },
    mistake: { bad: "שואלים «מה עושה הקוד?» ו-Bob עונה נכון אבל התשובה לא מסייעת — כי השאלה לא מוגדרת.", good: "«הסבר את המסלול מ-submit הטופס עד התגובה מה-DB — שכבה אחת בכל פעם»." },
    lab: ["פתחו TaskFlow ב-Ask.", "בקשו מ-Bob: «זהה קובץ UI, קובץ API, וקובץ DB».", "ציירו flow diagram מהלחיצה עד ה-DB.", "בקשו מ-Bob לתאר מה קורה ב-error case — שגיאת validation.", "תעדו: האם ה-flow הגיוני? האם גיליתם שכבה שציפיתם לה במקום אחר?", "הצלחה = יש לכם diagram מדויק עם 4 שכבות וזיהוי ברור של קובץ כל שכבה."],
    exercise: "בחרו פעולה אחת מאפליקציה שאתם מכירים (למשל «חיפוש») ופרקו אותה ל-4 שכבות.",
    quiz: [
      { q: "מה ההבדל בין Frontend ל-Backend?", a: "Frontend מציג ואוסף קלט; Backend מחיל כללים ומדבר עם DB. Frontend לא אמור לסמוך על נתונים מהדפדפן." },
      { q: "למה API אינו מסד נתונים?", a: "API הוא ממשק — דרך לבקש פעולות. DB הוא המקום שבו הנתונים חיים. API קורא/כותב ל-DB." },
      { q: "מה קורה למידע ששמור רק בזיכרון?", a: "נמחק ברענון/סגירה. לכן מידע עסקי חייב ב-DB או אחסון מתאים." },
      { q: "מה זה Stateless API ולמה זה חשוב?", a: "כל request עצמאי — השרת לא מסתמך על מה ששלחת קודם. זה מאפשר scale horizontal ומונע באגים של state פג-תוקף." },
      { q: "API מחזיר 200 על כל request. מה הבעיה?", a: "מחליא — הלקוח לא יכול לדעת אם הפעולה הצליחה. 400/404/500 הם חלק מה-contract ומאפשרים טיפול שגיאות תקין." },
    ],
    summary: ["מערכת = שכבות עם תפקידים ברורים.", "מסלול מידע אחד עדיף על «להבין הכל».", "Ask Mode מתאים לחקירה לפני שינוי.", "ראיה = diagram או הסבר שניתן לבדוק."],
  },
  {
    num: 2,
    title: "סביבת העבודה של המפתח",
    subtitle: "IBM Bob IDE, קבצים ופקודות הפעלה",
    phase: "foundation",
    time: "30 דק'",
    intro: "סביבת הפיתוח היא שולחן העבודה שלכם. Explorer, Editor, Terminal ו-Bob Chat — כשיודעים מה כל חלק עושה, פחות מפחדים משגיאות.",
    concepts: [
      { term: "Explorer", def: "עץ הקבצים — מבט על מבנה הפרויקט.", example: "app/, templates/, requirements.txt.", pitfall: "לערוך קובץ לא נכון כי לא בדקתם נתיב." },
      { term: "Editor", def: "קריאה ועריכת קוד.", example: "שינוי tasks.html.", pitfall: "שינוי בלי Diff review." },
      { term: "Terminal", def: "הרצת פקודות: python, pip, git, בדיקות.", example: "python app.py", pitfall: "הרצת פקודה לא מוכרת בלי Ask." },
      { term: "Build & Run", def: "Run = הפעלה מקומית. Build = הכנת תוצר לפריסה כשצריך.", example: "python app.py → הפעלה מקומית", pitfall: "לבלבל בין סביבת פיתוח לפריסה." },
      { term: "requirements.txt", def: "רשימת חבילות Python בפרויקט. שם מגדירים מה צריך להתקין כדי להריץ.", example: "flask==3.0.0", pitfall: "להתקין חבילה ידנית בלי לעדכן requirements.txt." },
      { term: "Error Log", def: "פלט שמראה מה קרה בזמן ההרצה. ב־Python traceback קוראים קודם את שורת ה־exception האחרונה כדי לזהות את סוג השגיאה וההודעה, ואז עולים דרך ה־stack frames כדי להבין מאיפה היא הגיעה.", example: "Traceback (most recent call last): ... ModuleNotFoundError: No module named 'tasks'", pitfall: "לקרוא רק את תחילת ה־traceback או להסתכל על שורה בודדת בלי ההקשר." },
    ],
    analogy: { text: "Explorer, Editor ו-Terminal הם שלוש נקודות מבט על אותו פרויקט: מבנה, תוכן, הרצה. כשיש שגיאת הרצה — Explorer מראה היכן הקובץ, Editor מראה את השורה, Terminal מראה את הודעת השגיאה. שלושתם חייבים לעבוד יחד.", bridge: "פתחו requirements.txt ב-Ask ובקשו מ-Bob: «אילו חבילות הפרויקט צריך, ומה יקרה אם חבילה חסרה?» — קבלו תשובה מפורשת לפני שמריצים." },
    bob: { modes: ["Ask"], workflow: "Ask + קריאת קבצי תצורה בלבד.", prompt: "In Ask mode: read requirements.txt and README. Explain install, run, and test. Do not run any commands.", promptWhy: "מצמצם לקבצי תצורה — פלט מדויק ובטוח." },
    mistake: { bad: "python app.py לא עובד — מריצים pip install מ-Stack Overflow בלי לדעת מה הוא מתקין.", good: "בקשו מ-Bob: «קראו requirements.txt ואמרו לי מה חסר לפי החבילות» — הסיבה לפני הפתרון." },
    lab: ["פתחו TaskFlow ב-Bob IDE.", "בקשו מ-Bob הסבר לכל חבילה ב-requirements.txt.", "הריצו python app.py אחרי שהבנתם מה הוא עושה.", "פתחו שגיאה מכוונת — מחקו חבילה — ובדקו מה מופיע בTerminal.", "תעדו: האם הצגתם ל-Bob את הודעת ה-exception ואת ה-traceback הרלוונטי, בלי להסתיר את ההקשר?", "הצלחה = הבנתם איך הפרויקט רץ בפיתוח וזיהיתם שגיאה אחת בעצמכם."],
    exercise: "מצאו 3 קבצים שלא יודעים מה תפקידם — שאלו Bob ב-Ask.",
    quiz: [
      { q: "הבדל קובץ מקור vs תצורה?", a: "מקור = לוגיקה/ממשק. תצורה = הגדרות (requirements.txt, .env)." },
      { q: "מה עושה requirements.txt?", a: "מגדיר אילו חבילות Python צריך להתקין כדי שהפרויקט ירוץ בצורה עקבית." },
      { q: "מאיפה מתחילים לקרוא Python traceback?", a: "מזהים את סוג ה־exception וההודעה בסוף, ואז עולים דרך ה־frames כדי לאתר את מקור הבעיה." },
      { q: "מה ההבדל בין pip install -r requirements.txt לבין python app.py?", a: "pip install מתקין את התלויות. python app.py מפעיל את האפליקציה. אם מדלגים על ההתקנה — ההרצה עלולה להיכשל." },
      { q: "שגיאה ב-Terminal מדווחת על קובץ שלא מכירים — מה עושים ראשון?", a: "בקשו מ-Bob לזהות את הקובץ ב-Explorer ולהסביר תפקידו לפני כל שינוי." },
    ],
    summary: ["IDE = Explorer + Editor + Terminal + Bob.", "Stack הקורס: Python + HTML/CSS/JS.", "קראו קבצי תצורה לפני הרצה.", "Terminal הוא כלי — לא מקור אמת."],
    deep: { title: "Stack הקורס", html: `<div class="prereq-grid"><div class="prereq-item"><strong>Python 3.11+</strong><span>שרת וכלים</span></div><div class="prereq-item"><strong>Git</strong><span>גרסאות</span></div><div class="prereq-item"><strong>דפדפן מודרני</strong><span>Chrome / Edge</span></div></div>` },
  },
  {
    num: 3,
    title: "Git ורשת הביטחון",
    subtitle: "ניהול גרסאות — להבין שינוי ולחזור אחורה",
    phase: "foundation",
    time: "30 דק'",
    intro: "Git הוא מחברת תיעוד של כל שינוי. עם Bob שעובד מהר, Git הוא רשת הביטחון — commit קטן, הודעה ברורה, אפשרות rollback.",
    concepts: [
      { term: "Commit", def: "צילום מצב עם הודעה.", example: "feat: add task filter", pitfall: "commit ענק עם 20 שינויים." },
      { term: "Branch", def: "קו פיתוח נפרד.", example: "feature/task-filter", pitfall: "לעבוד ישירות על main בלי בדיקה." },
      { term: "Diff", def: "השוואה לפני/אחרי.", example: "git diff", pitfall: "לא לקרוא Diff לפני commit." },
      { term: "Rollback", def: "חזרה לגרסה תקינה. לפני commit: git restore . | אחרי commit: git revert", example: "git restore . לביטול שינויים מקומיים", pitfall: "למחוק היסטוריה ב-force push." },
      { term: "Commit Message", def: "תיאור השינוי בפורמט type: subject. ה-type הנפוץ: feat, fix, refactor, docs, test.", example: "fix: prevent duplicate task on double-submit", pitfall: "«update» או «wip» — חסרי ערך בלי subject ספציפי." },
      { term: ".gitignore", def: "רשימת קבצים שGit לא עוקב אחריהם. חיוני לסינון .env, node_modules, build artifacts.", example: ".env לא נכנס ל-repo — מונע חשיפת secrets", pitfall: "לשכוח להוסיף .env ל-.gitignore לפני commit ראשון." },
    ],
    analogy: { text: "commit הוא checkpoint — נקודת חזרה ידועה. בלי commit לפני שינוי גדול של Bob, ה-diff מכסה עשרות קבצים בבת אחת ואי אפשר לדעת מה שייך לשינוי המתוכנן ומה הוסיף Bob מיוזמתו. Rollback הופך ל-«מחיקת הכל» במקום «חזרה לנקודה X».", bridge: "לפני שמבקשים מ-Bob שינוי: הריצו «git status» ו-«git diff» ב-Ask. אם אין clean working tree — commitו ראשון. בדקו: האם commit message מסביר למה, לא רק מה?" },
    bob: { modes: ["Ask", "Agent"], workflow: "Agent רק אחרי commit; שינויים קטנים.", prompt: "Show git status and git diff. Summarize changes in one line per file. Do not commit.", promptWhy: "מכריח review לפני פעולה." },
    mistake: { bad: "«תתקן הכל» בלי commit — אין נקודת חזרה. Bob שינה 12 קבצים; לא ברור מה נדרש ומה יוזמה.", good: "commit clean → prompt מוגדר → שינוי אחד → diff → commit עם הסבר." },
    lab: ["git init / clone TaskFlow.", "commit ראשון: «init: add TaskFlow project structure».", "בקשו מ-Bob שינוי קטן ב-CSS.", "הריצו git diff — קראו כל שינוי.", "commitו עם message שמסביר את הסיבה.", "הצלחה = git log מראה שני commits עם messages מובנים, וה-diff של כל commit ברור."],
    exercise: "צרו branch, שינוי, merge — תעדו כל שלב.",
    quiz: [
      { q: "מתי commit?", a: "אחרי יחידת עבודה שלמה ונבדקת — לא באמצע." },
      { q: "למה Diff לפני Agent?", a: "לראות בדיוק מה השתנה — לא לסמוך על «סיימתי»." },
      { q: "Branch vs main?", a: "Branch = ניסוי מבודד; main = יציב." },
      { q: "commit message טוב נראה איך?", a: "type: subject קצר ומדויק. «fix: prevent duplicate task on double-submit» — לא «update» או «changes»." },
      { q: "למה .gitignore חייב להיות בcommit הראשון?", a: "אם .env נכנס ל-repo — secrets דולפים לhistory גם אחרי מחיקה. git filter-branch מורכב ואינו פתרון מושלם." },
    ],
    summary: ["Commit קטן = rollback קל.", "Diff הוא חבר — לא אויב.", "Bob + Git = מהירות + ביטחון.", "אל ת-force push ל-main."],
  },
  {
    num: 4,
    title: "יסודות תכנות ללא עומס תחבירי",
    subtitle: "רעיונות לפני סימנים ושפות",
    phase: "foundation",
    time: "25 דק'",
    intro: "תכנות = הוראות, החלטות, חזרות ומבנים. Bob כותב תחביר; אתם צריכים להבין לוגיקה.",
    concepts: [
      { term: "משתנה", def: "שם לערך.", example: "taskTitle = «לסיים PRD»", pitfall: "שם לא ברור." },
      { term: "תנאי", def: "if/else — בחירה.", example: "if status === 'done' → hide", pitfall: "בלי else — edge cases." },
      { term: "לולאה", def: "חזרה על פעולה.", example: "tasks.forEach(render)", pitfall: "לולאה אינסופית." },
      { term: "פונקציה", def: "יחידת עבודה עם שם.", example: "createTask(title)", pitfall: "פונקציה שעושה 5 דברים." },
      { term: "הערך החוזר (return)", def: "מה הפונקציה מחזירה — ה-output המפורש. בלי return — הפונקציה מחזירה undefined.", example: "function add(a, b) { return a + b } ← הפלט הוא a+b, לא undefined", pitfall: "פונקציה שמשנה state חיצוני במקום להחזיר ערך — קשה לבדיקה." },
      { term: "Scope", def: "היכן משתנה גלוי. משתנה בתוך פונקציה — לא גלוי מחוצה לה.", example: "const total = tasks.reduce(sum, 0) — total גלוי רק בבלוק הזה", pitfall: "הצהרה על let בתוך if — לא גלוי מחוץ לבלוק ב-JS." },
    ],
    analogy: { text: "pseudocode מפריד בין לוגיקה לבין תחביר. כשמבינים את ה-if/else בעברית פשוטה — שגיאת compilation אינה מבלבלת: ברור שהלוגיקה נכונה, ורק הסימנים צריכים תיקון. אם לא הבנתם את ה-pseudocode — אין טעם לקרוא את הקוד.", bridge: "מצאו את createTask ב-TaskFlow. בקשו מ-Bob pseudocode שלה. בדקו: האם ה-pseudocode מסביר את כל ה-edge cases — כגון title ריק, משתמש לא מחובר? אם לא — הוסיפו אותם לפני שמאשרים קוד." },
    bob: { modes: ["Ask"], workflow: "Ask להסבר לוגיקה — לא קוד מלא.", prompt: "Explain createTask in @api/tasks.js as pseudocode. Do not change any code.", promptWhy: "Pseudocode = הבנה בלי תחביר." },
    mistake: { bad: "Bob כתב קוד עם if nested של 4 רמות — אישרתם כי נראה תקין.", good: "בקשו pseudocode ראשון. אם ה-pseudocode לא מובן לכם — הקוד לא יהיה תקין." },
    lab: ["מצאו פונקציה ב-TaskFlow.", "בקשו מ-Bob pseudocode.", "זהו: input, output, conditions, edge cases.", "כתבו pseudocode משלכם לפונקציה שכתב Bob.", "השוו — מצאו את ההבדל.", "הצלחה = זיהיתם edge case אחד שהpseudocode של Bob לא כיסה."],
    exercise: "תארו «מחיקת משימה» ב-pseudocode — 5 שורות max.",
    quiz: [
      { q: "משתנה vs קבוע?", a: "משתנה משתנה; קבוע (const) — לא." },
      { q: "למה פונקציה קצרה?", a: "קל לבדוק, לשם, לשכפל." },
      { q: "תנאי בלי else?", a: "מצבים לא צפויים נשברים בשקט." },
      { q: "מה מחזירה פונקציה ללא return?", a: "undefined — לא שגיאה, אבל כל קוד שמשתמש בתוצאה שלה יקבל undefined בשקט." },
      { q: "Scope — למה זה חשוב?", a: "משתנה שמוצהר בתוך if לא גלוי אחרי הבלוק. Bob לפעמים מכריז בלוקלי ומשתמש גלובלית — בדקו scope בdiff." },
    ],
    summary: ["לוגיקה > תחביר.", "Pseudocode לפני Agent.", "פונקציה = עשה דבר אחד.", "שאלו «מה יקרה אם…»."],
  },
  {
    num: 5,
    title: "Bob כשותף למחזור חיי הפיתוח",
    subtitle: "מה Bob עושה היטב, מה לא, ומי אחראי",
    phase: "bob",
    time: "30 דק'",
    intro: "Bob קורא, מתכנן, עורך ומריץ — אבל אין לו גישה לכוונה העסקית שלכם. הוא משלים חוסרים בהנחות. האחריות נשארת אצלכם.",
    concepts: [
      { term: "AI SDLC Partner", def: "סיוע בכל שלבי הפיתוח — לא החלפה.", example: "PRD → Plan → Code → Test", pitfall: "«Bob יבנה הכל»." },
      { term: "Context", def: "מה Bob רואה במשימה.", example: "@AGENTS.md + @src/", pitfall: "context ישן/שגוי." },
      { term: "הנחה", def: "מה Bob ממלא כשחסר מידע.", example: "«כנראה SQLite»", pitfall: "לא לגלות הנחות." },
      { term: "אחריות אנושית", def: "אתם מאשרים, בודקים, חותמים.", example: "Diff review לפני merge", pitfall: "approve בלי קריאה." },
      { term: "Hallucination", def: "Bob מייצר עובדה שגויה בביטחון מלא — API שלא קיים, פונקציה עם שם לא נכון, ספרייה מומצאת.", example: "«השתמשו ב-express.parseJson() — פונקציה שלא קיימת»", pitfall: "לא לבדוק documentation ולהניח שהפונקציה קיימת." },
      { term: "Verification", def: "בדיקה אקטיבית שהפלט נכון: tests, curl, console log, docs check.", example: "curl localhost:3000/api/tasks — מאמת שה-endpoint קיים ומחזיר JSON", pitfall: "«נראה נכון» ≠ עובד. Verification = ראיה." },
    ],
    analogy: { text: "Bob פועל על Context שסיפקתם — אם הContext חסר, הוא ממלא פערים בהנחות סבירות אך לא מאומתות. תוצאה נכונה בניסוח ≠ תוצאה נכונה בפועל. ה-diff ו-test הם הראיה היחידה; approve בלי קריאה הוא חתימה על מסמך שלא קראתם.", bridge: "שלחו ל-Bob בקשה עמומה: «שפר את TaskFlow». קבלו תשובה. בדקו: כמה הנחות זיהיתם בתשובה? שכתבו את הבקשה עם CGCA ושלחו שוב — מה השתנה?" },
    bob: { modes: ["Ask"], workflow: "בקשה לחשוף הנחות לפני כל פעולה.", prompt: "Before any action: write what you understood, list assumptions, ask blocking questions, and propose how to verify. Do not change code.", promptWhy: "מונע «פתרון נכון לבעיה לא נכונה»." },
    mistake: { bad: "Bob הציע להוסיף Redis לcache — אישרתם. לא שאלתם: האם TaskFlow בכלל סובל מbottleneck שRedisיפתור?", good: "«לפני כל שינוי: מה הנחת? מה הראיה שזו הבעיה האמיתית?»" },
    lab: ["בקשה עמומה: «שפר את האפליקציה».", "רשמו כמה הנחות Bob הכניס.", "שכתבו בקשה עם Goal + AC.", "השוו תוצאות — כמה הנחות נותרו?", "בדקו פונקציה אחת שBob הציע: האם היא קיימת? הריצו curl.", "הצלחה = מצאתם הנחה אחת לא מוצהרת ואמתתם אותה (או דחיתם)."],
    exercise: "כתבו בקשה גרועה + גרסה מתוקנת — 3 הבדלים.",
    quiz: [
      { q: "למה Bob פותר בעיה לא נכונה?", a: "חסר context / Goal / AC — הוא מנחש." },
      { q: "הצעה vs ראיה?", a: "הצעה = טענה; ראיה = diff, test, log." },
      { q: "מי אחראי על קוד AI?", a: "המפתח שאישר merge." },
    ],
    summary: ["Bob = שותף, לא בעלים.", "חשפו הנחות תמיד.", "ראיה > ביטחון.", "אחריות לא עוברת."],
  },
  {
    num: 6,
    title: "מצבי Ask, Plan ו-Agent",
    subtitle: "בחירת Mode לפי מטרה וסיכון",
    phase: "bob",
    time: "25 דק'",
    intro: "שלושה מצבים — שלוש רמות סיכון. Ask = 0 שינויים. Plan = תכנון וכתיבת קבצי plan, לא קוד אפליקציה. Agent = ביצוע. הבחירה הנכונה חוסכת rollback.",
    concepts: [
      { term: "Ask", def: "שאלות, הסבר, קריאה — בלי edit.", example: "«מה עושה הקובץ?»", pitfall: "Ask כשצריך Plan." },
      { term: "Plan", def: "תוכנית לפני קוד. יכול לכתוב קבצי plan (למשל plan/feature.md) — לא קוד אפליקציה.", example: "רשימת קבצים + שלבים + risks", pitfall: "Plan שלא קוראים." },
      { term: "Agent", def: "עריכה, הרצה, שינוי.", example: "מימוש שלב 1", pitfall: "Agent בלי Plan/AC." },
      { term: "Escalation", def: "מעבר מדורג: Ask→Plan→Agent.", example: "חקירה → תכנון → שלב 1", pitfall: "קפיצה ישר ל-Agent." },
      { term: "Scope Creep ב-Agent", def: "Agent שמתחיל בשינוי אחד ומרחיב לשינויים נוספים שלא בוקשו.", example: "בוקש «תקן הודעת שגיאה» — Bob שינה גם ה-validation logic וה-error handler", pitfall: "לאשר diff בלי לקרוא — הרחבה עלולה לשבור behavior קיים." },
      { term: "Plan Review", def: "קריאה אנושית של Plan לפני ביצוע — לא rubber stamp.", example: "Plan כולל «נעדכן DB» — שאלו: איזה migration? Rollback?", pitfall: "approve מהיר של plan ארוך — הסיכון מסתתר בפרטים." },
    ],
    analogy: { text: "שלושת המצבים הם רמות סיכון גוברות: Ask לא כותב שורת קוד, Plan כותב קבצי תכנון בלבד, Agent משנה קוד אמיתי. ביצוע ב-Agent Mode ללא Plan שקול לשינוי ישיר ב-main בלי branch — מהיר, אך ללא נקודת חזרה ברורה.", bridge: "בחרו משימה ב-TaskFlow: «הוסף סינון Done». כתבו — לפני שמבקשים מ-Bob — באיזה mode תתחילו, מה תבדקו בPlan, ומה ה-stop condition של ה-Agent. השוו לתוצאה האמיתית." },
    diagram: `<div class="mode-row"><span class="mode-pill mode-ask">Ask — חקירה</span><span class="mode-pill mode-plan">Plan — תכנון</span><span class="mode-pill mode-agent">Agent — ביצוע</span></div>`,
    bob: { modes: ["Ask", "Plan", "Agent"], workflow: "תמיד Escalation — לא קפיצה.", prompt: "Task: add a Done filter to TaskFlow. Start in Plan: files, steps, and acceptance criteria. Do not edit files.", promptWhy: "Plan לפני Agent = roadmap." },
    mistake: { bad: "בוקש «תקן שגיאת CSS» — Bob הוסיף גם refactor ל-JS ו-2 קבצים חדשים. אישרתם.", good: "הגדירו Scope ב-prompt: «Edit only @public/style.css. No JS changes.» — ו-review diff לפני approve." },
    lab: ["בחרו משימה: «הוסף סינון Done».", "Ask: מפו קבצים מעורבים.", "Plan: שלבים + AC.", "Agent: שלב 1 בלבד — Stop.", "קראו diff: האם Bob חרג מה-scope?", "הצלחה = גילוי מקרה אחד בו Bob ניסה לשנות מעבר למה שבוקש."],
    exercise: "סווגו 5 משימות ל-Ask/Plan/Agent.",
    quiz: [
      { q: "מתי Plan?", a: "שינוי >1 קובץ / לא ברור / סיכון." },
      { q: "Agent בלי Plan?", a: "שינויים לא צפויים — rollback." },
      { q: "Ask מספיק?", a: "כשצריך רק הבנה — לא שינוי." },
      { q: "Scope Creep — איך מזהים בdiff?", a: "Bob שינה קבצים שלא ציינתם ב-prompt. כל קובץ בdiff שלא הוזכר במפורש = scope creep פוטנציאלי." },
      { q: "Plan review — מה מחפשים?", a: "הנחות לא מוצהרות («לפי הצורך»), שינויי DB ללא migration, שלבים ללא AC ברור." },
    ],
    summary: ["Mode = רמת סיכון.", "Escalation, לא קפיצה.", "Plan = חוזה.", "Agent = שלבים קטנים."],
  },
  {
    num: 7,
    title: "כתיבת הנחיות יעילות ל-Bob",
    subtitle: "Prompt ברור, מוגבל וניתן לבדיקה",
    phase: "bob",
    time: "35 דק'",
    intro: "Prompt טוב = הזמנת עבודה: Context, Goal, Constraints, Acceptance Criteria. זה ההבדל בין demo ל-production.",
    concepts: [
      { term: "Context", def: "רקע + @קבצים.", example: "@src/tasks/", pitfall: "בלי קונטקסט בוב מנחש." },
      { term: "Goal", def: "תוצאה אחת.", example: "סינון All/Open/Done", pitfall: "3 features בבקשה." },
      { term: "Constraints", def: "מה אסור.", example: "בלי ספרייה חדשה", pitfall: "לא לציין out of scope." },
      { term: "Acceptance Criteria", def: "תנאים מדידים.", example: "3 מצבים + tests", pitfall: "«שיעבוד»." },
      { term: "Out of Scope", def: "הצהרה מפורשת על מה לא לגעת בו.", example: "Out of scope: לא לשנות @api/tasks.js — רק UI", pitfall: "להשאיר implicit — Bob ישנה גם Backend אם לא נאמר אחרת." },
      { term: "Prompt Iteration", def: "Prompt ראשון לעולם לא מושלם — זו טיוטה. Plan review חושף מה לתקן לפני Agent.", example: "Prompt v1 → Plan → «חסר migration mention» → Prompt v2 → Plan מתוקן → Agent", pitfall: "לאשר Plan v1 מבלי לעדכן — Agent מממש את הטיוטה." },
    ],
    analogy: { text: "מודל שפה מייצר את הפלט הסביר ביותר לפי הקלט שקיבל. Context חסר → הנחות. Goal עמום → scope creep. ללא Acceptance Criteria — אי אפשר לדעת אם התוצאה נכונה עד שבודקים ידנית. CGCA הוא המינימום שהופך בקשה לניתנת לבדיקה.", bridge: "כתבו CGCA ל-«סינון Done» ב-TaskFlow. שלחו ל-Bob ב-Plan. קראו את ה-Plan — מצאו item אחד שBob הניח ולא ציינתם. תקנו את ה-CGCA ושלחו שוב." },
    bob: { modes: ["Plan"], workflow: "CGCA template לכל בקשה.", prompt: "Context: @src/tasks\nGoal: Add All / Open / Done filter\nConstraints: vanilla JS, no new libraries\nAC: all three states work + a unit test\nShow a Plan before editing.", promptWhy: "CGCA = ניתן לבדיקה." },
    mistake: { bad: "CGCA עם AC שכתוב «הסינון יעבוד» — Bob לא יכול לבדוק מה זה אומר.", good: "AC: «כפתור Done מסנן רשימה ל-tasks עם status=done בלבד; כפתור All מחזיר הכל; unit test לכל state»." },
    compare: { bad: "Improve the app", good: "Context: @app.js\nGoal: Add a Clear completed button\nConstraints: reuse existing CSS\nAC: click removes done items from the UI" },
    lab: ["כתבו Prompt שורה אחת ל-TaskFlow filter.", "זהו 3 חסרים (Context/Goal/Constraints/AC).", "הרחיבו ל-CGCA מלא.", "שלחו ל-Plan — קראו Plan.", "תקנו Prompt לפי Plan.", "הצלחה = AC שלכם testable: כן/לא, מספר מדויק, מצב קצה אחד לפחות."],
    exercise: "CGCA ל-«מחיקת משימה עם אישור».",
    quiz: [
      { q: "AC מדיד?", a: "כן/לא, מספר, test — לא «יפה»." },
      { q: "Out of Scope?", a: "מונע scope creep." },
      { q: "מתי @?", a: "כשיש קובץ/תיקייה ספציפיים." },
      { q: "מדוע Prompt iteration הכרחי?", a: "Prompt ראשון = טיוטה. Plan חושף הנחות. רק אחרי תיקון Prompt מבוסס Plan, הAgent מממש נכון." },
      { q: "Out of Scope implicit vs explicit?", a: "Implicit = Bob משנה מה שנראה לו רלוונטי. Explicit = «Do not touch @api/» — גבול פיזי שBob מכבד." },
    ],
    summary: ["CGCA = מינימום.", "בקשה אחת = feature אחד.", "AC לפני Agent.", "שמרו templates."],
    deep: { title: "תבנית CGCA", html: `<pre class="prompt">Context: @path/to/files
Goal: [one outcome]
Constraints: [stack, what is forbidden]
Acceptance: [measurable conditions]
Out of scope: [what not to do]</pre>` },
  },
  {
    num: 8,
    title: "Context, /init ו-AGENTS.md",
    subtitle: "זיכרון פרויקט מדויק ומתוחזק",
    phase: "bob",
    time: "30 דק'",
    intro: "שיחה חדשה = הקשר מוגבל. יש הבדל בין מה Bob רואה עכשיו (@ ו-Prompt) לבין מה שנטען מ-AGENTS.md בכל שיחה. /init מייצר טיוטה — חובה לבדוק ולתחזק. חשוב: AGENTS.md צריך להיות קצר — הוא נטען לחלון ההקשר בכל שיחה ומתחרה על מקום.",
    concepts: [
      { term: "/init", def: "סריקה + יצירת context files.", example: "AGENTS.md + .bob/rules-agent/ + rules-plan/ + rules-ask/", pitfall: "להניח שהכל נכון." },
      { term: "AGENTS.md", def: "מדריך: מטרה, מבנה, כללים. קצר = יעיל. ארוך מדי = Bob מתעלם ממה שקבור בסוף.", example: "TaskFlow = task manager", pitfall: "AGENTS.md ישן או עמוס מדי." },
      { term: "Context Budget", def: "לחלון ההקשר יש גודל מוגבל. יותר קבצים ≠ תוצאות טובות יותר.", example: "AGENTS.md קצר + @קובץ ספציפי עדיף על @כל-הפרויקט", pitfall: "לצרף הכל בתקווה שBob יבין טוב יותר." },
      { term: "תחזוקה", def: "עדכון אחרי שינוי stack.", example: "הוספת Flask → עדכון AGENTS", pitfall: "init פעם אחת." },
      { term: "Rules vs AGENTS.md", def: "AGENTS.md = מה הפרויקט הוא. Rules (.bob/rules-*/) = איך Bob מתנהג בו. שניהם נטענים בכל שיחה — שניהם גוזלים context.", example: "AGENTS: «Stack: Python+SQLite». Rule: «תמיד הרץ tests לפני done».", pitfall: "לשים הכל ב-AGENTS.md — Rules שייכות לקובץ rules, לא ל-AGENTS." },
      { term: "Staleness", def: "AGENTS.md שמתאר stack ישן — Bob מבוסס על הנחות שגויות.", example: "AGENTS: «DB: SQLite» — בפועל מיגרתם ל-PostgreSQL. Bob מייצר SQLite-specific queries.", pitfall: "לא לעדכן AGENTS אחרי שינוי stack — התוצאה: קוד שנראה נכון, לא עובד בפרודקשן." },
    ],
    analogy: { text: "בכל שיחה חדשה, Bob מתחיל בלי היסטוריה — הוא קורא את AGENTS.md מחדש. קובץ ארוך ולא מדויק פוגע פעמיים: הוא תופס context budget יקר, ומוביל Bob לפעול על הנחות ישנות. AGENTS.md מדויק + קצר = השקעה שמשתלמת בכל שיחה.", bridge: "בקשו מ-Bob: «קרא AGENTS.md ואת requirements.txt — רשום רק את הסתירות». כמה מצאתם? תקנו אותם ידנית." },
    bob: { modes: ["Ask"], workflow: "השוואת AGENTS.md למציאות.", prompt: "Read AGENTS.md and compare it to requirements.txt and the project tree. List inaccuracies only. Do not change files.", promptWhy: "Audit לפני trust." },
    mistake: { bad: "AGENTS.md עם 40 שורות שמתארות כל קובץ בפרויקט — Bob מתעלם מהחצי השני.", good: "AGENTS.md של 15 שורות: stack, commands, 3 כללים עסקיים קריטיים, ומה Bob לא יכול לדעת מהקוד." },
    lab: ["הריצו /init על TaskFlow.", "בקשו מ-Bob לבדוק AGENTS.md מול requirements.txt.", "מצאו סתירה אחת לפחות.", "הוסיפו כלל עסקי שלא ניתן ללמוד מהקוד.", "commitו AGENTS.md מעודכן.", "הצלחה = AGENTS.md קצר מ-20 שורות, מדויק, ומכיל לפחות מידע עסקי אחד שאינו בקוד."],
    exercise: "רשימת 5 דברים ש-AGENTS חייב לכלול.",
    quiz: [
      { q: "למה context קבוע?", a: "שיחות חדשות — בלי היסטוריה." },
      { q: "מתי init מחדש?", a: "שינוי stack, מבנה, כללים." },
      { q: "מידע עסקי ידני?", a: "מדיניות, SLA, מונחים — לא בקוד." },
      { q: "AGENTS.md ארוך מדי — מה ההשפעה?", a: "Bob מתעלם ממה שקבור בסוף. גם תופס context budget שיכול לשמש לקוד אמיתי." },
      { q: "Staleness — דוגמה לתוצאה?", a: "AGENTS: SQLite. מציאות: PostgreSQL. Bob מייצר queries עם SQLite syntax שנכשלות בproduction." },
    ],
    summary: ["/init = טיוטה.", "שיחה ≠ קובץ: @ למשימה, AGENTS לקבוע.", "AGENTS.md קצר ומדויק — context budget מוגבל.", "Audit לפני Agent."],
    deep: { title: "הרחבה: חוברת הקשר וזיכרון", html: `<p>פירוט מלא — ארבע שכבות הקשר, מה לשים ב־Prompt מול AGENTS.md, ותבנית TaskFlow — בחוברת <a href="IBM_Bob_Developer_Context_Memory_Guide_HE.html">לעבוד עם IBM Bob כמו שותף פיתוח</a>.</p>
<pre class="code-block"># TaskFlow
## Stack: Python, Flask, SQLite, Vanilla JS
## Commands: python app.py | pytest
## Rules: Agent must run tests before done
## Business: task status = open | done only</pre>` },
  },
  {
    num: 9,
    title: "גבולות גישה והרשאות",
    subtitle: "רק הסמכויות הדרושות למשימה",
    phase: "bob",
    time: "25 דק'",
    intro: "Agent עם הרשאות מלאות = סיכון. Read-only לחקירה, write מוגבל למימוש, deny ל-production secrets.",
    concepts: [
      { term: "Least Privilege", def: "מינימום הרשאות.", example: "Ask = read only", pitfall: "all access default." },
      { term: "Scope", def: "אילו קבצים/פקודות.", example: "רק @src/components", pitfall: "«כל הפרויקט»." },
      { term: "Secrets", def: "מפתחות, .env — out of bounds.", example: "אל תקרא .env", pitfall: "commit secrets." },
      { term: "Approval Gate", def: "אישור לפני פעולה מסוכנת.", example: "לפני rm, deploy", pitfall: "auto-approve." },
      { term: ".bobignore", def: "קובץ שמגדיר מה Bob לא יכול לקרוא — מקביל ל-.gitignore. secrets, .env, node_modules.", example: ".env\nsecrets/\n*.pem\nnode_modules/", pitfall: "לא ליצור .bobignore — כל @ רחב עלול לכלול secrets בcontext." },
      { term: "Blast Radius", def: "כמה נזק יכול לקרות אם Agent יפרש prompt לא נכון. Scope מצמצם blast radius.", example: "Scope = @public/css → נזק מקסימלי = עיצוב שגוי. Scope = @/ → נזק מקסימלי = DB נמחק.", pitfall: "להניח שBob לא יעשה פעולות destructive ללא הוראה מפורשת." },
    ],
    analogy: { text: "Agent עם גישה לכל הפרויקט ולכל הפקודות הוא סיכון מובנה: שגיאה בפרשנות prompt עלולה לשנות קבצי production, למחוק נתונים או לכתוב secrets ל-log. Scope מוגבל ב-prompt מצמצם את radius הנזק האפשרי.", bridge: "לפני משימת CSS: כתבו prompt עם Scope מפורש. לאחר ביצוע — בדקו diff: האם Bob נשאר בScope? האם .env נגע?" },
    bob: { modes: ["Agent"], workflow: "הגבילו scope ב-prompt + settings.", prompt: "Edit only @public/css. Do not touch @.env or @requirements.txt. Show the diff.", promptWhy: "Scope = גבול פיזי." },
    mistake: { bad: "«שפר את העיצוב» בלי Scope. Bob שינה HTML, JS, CSS ו-requirements.txt להוספת ספרייה חדשה.", good: "«Edit only @public/style.css. Do not add libraries. No JS changes.» — ואז review diff." },
    lab: ["צרו .bobignore עם .env ו-secrets/.", "משימה read-only — Ask בלבד.", "משימת CSS — הגדירו Scope צר.", "לאחר Agent: בדקו diff — האם חרג מScope?", "תעדו: מה ה-blast radius של כל משימה שביצעתם?", "הצלחה = diff לא מכיל קבצים מחוץ לScope שהגדרתם."],
    exercise: "רשימת «מותר/אסור» ל-refactor UI.",
    quiz: [
      { q: "Least Privilege?", a: "רק מה שנדרש — לא יותר." },
      { q: "למה deny .env?", a: "secrets לא ב-context AI." },
      { q: "Approval Gate?", a: "פעולות irreversible — אישור אנושי." },
      { q: "מה .bobignore עושה?", a: "מגדיר קבצים שBob לא יכול לגשת אליהם — מונע חשיפת secrets גם דרך @ רחב." },
      { q: "Blast Radius — מה ההבדל בין Scope צר לרחב?", a: "Scope = @public/css: נזק = עיצוב בלבד. Scope = @: נזק פוטנציאלי = כל הפרויקט כולל DB ו-secrets." },
    ],
    summary: ["הרשאות = scope.", "Secrets out.", "Approve מסוכן.", "Read לפני write."],
  },
  {
    num: 10,
    title: "Rules, Custom Modes וסטנדרטיזציה",
    subtitle: "כללים עקביים לכל הפרויקט",
    phase: "bob",
    time: "30 דק'",
    intro: "Rules = התנהגות קבועה של Bob. Custom Modes = תפקידים (Reviewer, Planner). סטנדרט = פחות variance בין sessions. מבנה: .bob/rules/ לכל המצבים, .bob/rules-agent/ / rules-plan/ / rules-ask/ לכל מצב.",
    concepts: [
      { term: "Rules", def: "הוראות ב-.bob/rules/ — חלות על כל המצבים.", example: "עברית בתגובות", pitfall: "100 rules — conflict." },
      { term: "Custom Mode", def: "persona + הרשאות.", example: "Reviewer: read + comment", pitfall: "mode בלי מטרה." },
      { term: "Convention", def: "סגנון קוד אחיד.", example: "camelCase JS", pitfall: "Bob ממציא סגנון." },
      { term: "Drift", def: "סטייה מהכללים.", example: "rules לא מעודכנות", pitfall: "ignore drift." },
      { term: "Rule Quality", def: "Rule טוב = ניתן לבדיקה, חל על כל session, לא סותר rule אחר.", example: "«כל Agent iteration מסתיים ב-pytest» — ניתן לבדוק", pitfall: "Rule ש-Bob לא יכול לאכוף — «כתוב קוד נקי» = לא testable ולא אכיף." },
      { term: "Mode-specific Rules", def: "Rules שחלות רק ב-mode מסוים: .bob/rules-agent/, rules-plan/, rules-ask/.", example: "rules-agent: «הרץ tests לפני done». rules-ask: «תמיד cite source».", pitfall: "לשים rules ספציפיות ל-Agent ב-.bob/rules/ הכללי — חלות גם ב-Ask ומבלבלות." },
    ],
    analogy: { text: "Rules הן הגדרות התנהגות קבועות שחוסכות הוראות חוזרות בכל prompt. בלי rules — Bob ממציא סגנון, בוחר שפה ומחליט על convention בכל שיחה. יותר מ-10–15 rules מסותרות פוגעות: Bob מתעלם ממה שקבור בסוף הרשימה.", bridge: "כתבו rule אחד ל-TaskFlow שיחסוך לכם הוראה חוזרת. בדקו: האם ה-rule testable? האם Bob יודע מתי הוא הפר אותו?" },
    bob: { modes: ["Plan"], workflow: "Rules קצרות, focused.", prompt: "Propose 5 rules for TaskFlow covering tests, commits, and scope. Do not create files yet.", promptWhy: "Plan rules — לא spam." },
    mistake: { bad: "20 rules — ביניהן «כתוב קוד מסודר» ו-«תמיד תסביר מה עשית». Bob מתעלם מהרשימה כולה.", good: "5 rules מדידות: «Run pytest before done», «No new Python packages without Ask first», «Scope to named files only»." },
    lab: ["כתבו 3 rules מדידות ל-TaskFlow.", "הניחו rule שBob יפר — בדקו האם הוא מציין זאת.", "עדכנו rule שלא עבד.", "commitו rules עם הסבר למה כל rule נוספה.", "הצלחה = כל rule שלכם ניתנת לבדיקה: אפשר לאמר «כן/לא — הRule הושמר»."],
    exercise: "Custom Mode «QA» — מה ההרשאות?",
    quiz: [
      { q: "Rules vs AGENTS?", a: "AGENTS = מה הפרויקט; Rules = איך Bob מתנהג בו." },
      { q: "Custom Mode?", a: "תפקיד + scope — לא רק שם." },
      { q: "Drift?", a: "עדכון rules כש-stack משתנה." },
      { q: "Rule שלא ניתן לאכוף — מה קורה?", a: "Bob מתעלם ממנה או מפרש לפי שיקול דעתו. Rule חייבת להיות בינארית — הושמרה / לא הושמרה." },
      { q: "מה ההבדל בין .bob/rules/ לבין .bob/rules-agent/?", a: "rules/ = חל על כל mode. rules-agent/ = רק ב-Agent. rules שמוגבלות ל-Agent לא צריכות לטעון ב-Ask." },
    ],
    summary: ["Rules קצרות.", ".bob/rules-agent/ rules-plan/ rules-ask/ — לכל מצב.", "Conventions ב-AGENTS.", "Review drift."],
  },
];
